services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_backend_template
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
       context: .
       dockerfile: build/Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - air_tmp:/app/tmp
    working_dir: /app
    command: air

volumes:
  pgdata:
  redisdata:
  air_tmp:
